version: 2

models:
      - name: silver_commodities
        description: "Tabela de staging para dados de commodities"
        columns:
          - name: data
            description: "Data da observação no formato AAA-MM-DD."
          - name: valor_fechamento
            description: "Preço do fechamento da commodity."
          - name: simbolo
            description: "Simbolo da commodity."

          - name: silver_movimentacao_commodities
        description: "Tabela de staging para movimentação de commodities"
        columns:
          - name: data
            description: "Data da transação no formato AAA-MM-DD."
          - name: simbolo
            description: "Simbolo da commodity."
          - name: acao
            description: "Tipo de transação (buy/sell)."
          - name: quantidade
            description: "Quantidade transicionada."