dw_commodities:
  outputs:
    dev:
      dbname: databasesales_8qy0
      host: dpg-da70i0ifngtc73bthrig-a.ohio-postgres.render.com
      pass: 8kLZo5gFfnYP0yf8t9VFBKc8oiVmHK9D
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres123
  target: dev
